### ISSUE TITLE
Print "done" after all commands are run

### ISSUE THREAD

**Issue by karbassi** [WeAllCode/tinybit-python#13]
It would be nice to see, in the terminal, that the commands have been sent to the robot and we're done. Currently, the students don't know if the robot has been ran or not.

**Comment by blainerothrock** [comment]
at the end of the program, the script prints "{ robot name } Done!"

```
(wac) ➜  python test.py

WAC-2463 Done!

(ble) ➜  tinybit-python git:(main) 
```
